allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
# minimumReleaseAge: 10080 # 7 days
minimumReleaseAge: 2880 # 2 days
minimumReleaseAgeExclude:
  - '@typescript-eslint/*'
  - '@playwright/*'
  - '@tanstack/*'
  - '@types/node'
